class AppStringEn {
  static const howAreYouFeeling = 'How are you feeling today?';
  static const yourname = 'Your Name';
  static const home = 'Home';
  static const refercode = 'Refer Code';
  static const forgotPassword = "Forgot Password";
  static const selectYouLikeToProceed = "Select how you’d like to proceed.";
  static const emailAddress = "Email Address";
  static const enterMail = "Enter Mail";
  static const sendCode = "Send Code";
  static const OTPVerification = "OTP Verification";
  static const enterCode = "Enter Code";
  static const next = "Next";
  static const newPassword = "New Password";
  static const confirmPassword = "Confirm Password";
  static const save = "Save";
  static const chooseYourLanguage = "Choose Your Language";
  static const eligetuidioma = "Elige tu idioma";
  static const usEnglish = "US English";
  static const whatsGood = "What's good? Welcome to Naculis";
  static const espanol = "🇲Español";
  static const espanolTr = "¿Qué onda? Bienvenido a Naculis";
  static const signIn = "Sign In";
  static const getStarted = "Let's Get Started";
  static const tellUsAboutYourself = "Tell us a bit about yourself";
  static const yourName = "Your Name";
  static const enterName = "Enter Name";
  static const password = "Password";
  static const enterPassword = "Enter Password";
  static const rememberMe = "Remember me ?";
  static const forgotPassword1 = "Forgot password?";
  static const dontHaveAccount = "Don’t have an account? ";
  static const signUp = "Sign Up ";
  static const phone = "Phone ";
  static const phoneHint = "+44 258 6649 565  ";
  static const passwordHint = "*** *** *** ";
  static const start = "Start ";
  static const Continue = "Continue ";
  static const type = "Type ";
  static const speak = "Speak ";
  static const submitYourAnswer = "Submit your answer ";
  static const typeYourAnswer = "Type Your Answer";
  static const congratulations = "Congratulations!";
  static const totalXP = "Total XP";
  static const amazing = "Amazing";
  static const earnedGems = "Earned Gems";
  static const shareResults = "Share Results";
  static const takeNewQuiz = "Take New Quiz";
  static const gotIt = "Got it";
  static const holdToSpeak = "Hold to Speak";
  static const leaderboard = "Leaderboard";
  static const lessonQuests = "Lesson Quests";
  static const autoTrackedQuests = "Auto-Tracked Quests";
  static const gemsAvailable = "Gems Available";
  static const exchange = "Exchange";
  static const heartRecharge = "Heart Recharge";
  static const restoreAllHeart =
      "Instantly restore all hearts to continue learning";
  static const heartsFull = "Hearts Full";
  static const alreadyMaxHeart = "Your hearts are already at maximum";
  static const premiumSubscription = "Premium Subscription";
  static const popular = "Popular";
  static const removeAdsUnlockPremium =
      "Remove ads and unlock premium features";
  static const perMonth = "Per month";
  static const subscribe = "Subscribe";
  static const gemToUSD = "Gem to USD";
  static const youCanWithDraw = "You Can Withdraw : ";
  static const paypalEmail = "Your PayPal Email ";
  static const withdrawToPayPal = "Withdraw to PayPal";
  static const selectPaymentGateway = "Select payment gateway";
  static const addNew = "Add New";
  static const paymentMethod = "Payment Method New";
  static const profile = "Profile";
  static const aiPersonalityAnalysis = "AI Personality analysis";
  static const generateAnalysis = "Generate Analysis";
  static const getPersonalizedInsights =
      "Get personalized insights based on your intro answers and chat interactions!";
  static const friends = "Friends";
  static const squadTogether = "Get your squad together!";
  static const inviteFriends = "Invite Friends";
  static const YourStats = "Your Stats";
  static const Hearts = "Hearts ";
  static const Level = "Level  ";
  static const DaySteark = "Day Steark  ";
  static const XP = "XP ";
  static const AccountDetails = "Account Details";
  static const PersonalInfo = "Personal Info";
  static const Notification = "Notification";
  static const referAFriend = "Refer a friend";
  static const SettingsAccessibility = "Settings & Accessibility";
  static const DarkMode = "Dark Mode";
  static const Voiceover = "Voiceover";
  static const Earn = "Earn";
  static const MyBalance = "My Balance";
  static const Support = "Support";
  static const ContactUS = "Contact US";
  static const LogOut = "Log Out";
  static const RefreshAnalysis = "Refresh Analysis";
  static const Phone = "Phone";
  static const Birthday = "Birthday";

  static const country = "Country";
  static const Save = "Save ";
  static const AvailableBalance = "Available Balance ";
  static const Withdarw = "Withdarw ";
  static const Activity = "Activity ";
  static const Received = "Received ";
  static const Requested = "Requested ";
  static const Rejected = "Rejected ";
  static const Pending = "Pending ";
  static const SubmitRequest = "Submit Request ";
  static const Amount = "Amount  ";
  static const PaymentMethod = "Payment Method";
  static const Notifications = "Notifications";
  static const Today = "Today ";
  static const Yesterday = "Yesterday ";
  static const ContactUs = "Contact Us ";
  static const writeInCommentBox = "Write in bellow box ";
  static const enterIssueTitle = "Enter the title of your issue";
  static const Title = "Title";
  static const Writehere = "Write here...";
  static const Send = "Send";
  static const ReferFriend = "Refer a Friend";
  static const ReferFriendAndGetOff = "Refer a Friend & Get 50% off";
  static const Refer = "Refer";
  static const alreadyHaveAccount = "'Already have an account?'";
  static const contactUs = 'Contact Us';
  static const contactSubtitle = 'Hello, how can we assist you?';
  static const titleLabel = 'Title';
  static const titleHint = 'Enter the title of your issue';
  static const messageLabel = 'Write in the box below';
  static const messageHint = 'Write here...';
  static const send = 'Send';
  static const chooseSlangTypes =
      'Choose the types of slang you use or want to help define';
  static const whatLanguageUsed = 'What language do you often use?';
  static const slangPathNote = 'This helps us tailor your slang path.';
  static const whatsYourVibe = "What's Your Vibe?";
  static const editProfile = "Edit Profile";

  // AppStringEn
  static const gender = 'Gender';
  static const lastName = 'Last Name';
  static const profileInfo = "Profile Info";
  static const aiAnalysis = "AI Analysis";
  static const analysisSummary =
      "Based on your profile, you're an English speaker with en-us dialect preferences. Your vibe selection (youth) suggests you're interested in authentic cultural experiences and community connections. Your emotional state (curious) indicates you're ready to engage with new learning experiences. You have a strong interest in street culture and community engagement, making you well-suited for exploring local scenes and building meaningful connections through language learning.";

  static const userName = "Kenn Denson"; // optional, or dynamic later
  static const userEmail = "israal123@gmail.com"; // optional, or dynamic later
  static const AiPersonalityAnalysis = "AI Personality Analysis";
  static const generateAnalysiss = "Generate Analysis";
  static const refreshAnalysis = "Refresh Analysis";
  static const accountDetails = "Account Details";
  static const personalInfo = "Personal Info";
  static const notification = "Notification";
  static const referAfriend = "Refer a friend";
  static const settings = "Settings & Accessibility";
  static const darkmode = "Dark Mode";
  static const changeLanguage = "Change Language";
  static const earn = "Earn";
  static const myBalance = "My Balance";
  static const support = "Support";
  static const contactUss = "Contact Us";
  static const logOut = "Log Out";
  static const getpersonality = "Get personalized insights based on your intro answers and chat interactions!";



}

class AppStringEs {

  static const profile = "Perfil";
  static const home = "Inicio";
  static const changeLanguage = "Cambiar idioma";
  static const earn = "Ganar";
  static const myBalance = "Mi saldo";
  static const support = "Soporte";
  static const contactUss = "Contáctanos";
  static const logOut = "Cerrar sesión";
  static const accountDetails = "Detalles de la cuenta";
  static const personalInfo = "Información personal";
  static const notification = "Notificación";
  static const referAfriend = "Invitar a un amigo";
  static const settings = "Configuración y accesibilidad";
  static const darkmode = "Modo oscuro";
  static const generateAnalysiss= "Generar análisis";
  static const refreshAnalysis= "Actualizar análisis";
  static const referAnalysis = "Generar análisis";

  static const getpersonality = "Obtén información personalizada basada en tus respuestas iniciales y tus interacciones en el chat.";
  static const AiPersonalityAnalysis = "Análisis de Personalidad con IA";

  static const userName = "Kenn Denson";
  static const userEmail = "israal123@gmail.com";

  static const profileInfo = "Información del perfil";
  static const aiAnalysis = "Análisis de IA";
  static const analysisSummary =
      "Según tu perfil, eres un hablante de inglés con preferencias de dialecto en-us. Tu selección de vibra (juventud) sugiere que te interesan las experiencias culturales auténticas y las conexiones comunitarias. Tu estado emocional (curioso) indica que estás listo para participar en nuevas experiencias de aprendizaje. Tienes un gran interés en la cultura urbana y el compromiso comunitario, lo que te hace adecuado para explorar escenas locales y construir conexiones significativas a través del aprendizaje de idiomas.";

  // AppStringEs
  static const gender = 'Género';
  static const lastName = 'Apellido';
  static const editProfile = "Editar perfil";
  static const whatsYourVibe = "¿Cuál es tu onda?";
  static const slangPathNote =
      'Esto nos ayuda a personalizar tu ruta de jerga.';
  static const whatLanguageUsed = '¿Qué idioma usas con frecuencia?';
  static const chooseSlangTypes =
      'Elige los tipos de jerga que usas o quieres ayudar a definir';
  static const howAreYouFeeling = '¿Cómo te sientes hoy?';
  static const contactUs = 'Contáctanos';
  static const contactSubtitle = 'Hola, ¿cómo podemos ayudarte?';
  static const titleLabel = 'Título';
  static const titleHint = 'Ingresa el título de tu problema';
  static const messageLabel = 'Escribe en el cuadro de abajo';
  static const messageHint = 'Escribe aquí...';
  static const send = 'Enviar';
  static const alreadyHaveAccount = "¿Ya tienes una cuenta?";
  static const forgotPassword = "¿Olvidaste tu contraseña?";
  static const selectYouLikeToProceed =
      "Selecciona cómo te gustaría continuar.";
  static const emailAddress = "Dirección de correo electrónico";
  static const enterMail = "Introduce el correo";
  static const sendCode = "Enviar código";
  static const OTPVerification = "Verificación OTP";
  static const enterCode = "Introduce el código";
  static const next = "Siguiente";
  static const newPassword = "Nueva contraseña";
  static const confirmPassword = "Confirmar contraseña";
  static const save = "Guardar";
  static const chooseYourLanguage = "Elige tu idioma";
  static const eligetuidioma = "Elige tu idioma";
  static const usEnglish = "Inglés (EE.UU.)";
  static const whatsGood = "¿Qué onda? Bienvenido a Naculis";
  static const espanol = "🇲Español";
  static const espanolTr = "¿Qué onda? Bienvenido a Naculis";
  static const signIn = "Iniciar sesión";
  static const getStarted = "Comencemos";
  static const tellUsAboutYourself = "Cuéntanos un poco sobre ti";
  static const yourName = "Tu nombre";
  static const enterName = "Introduce tu nombre";
  static const password = "Contraseña";
  static const enterPassword = "Introduce la contraseña";
  static const rememberMe = "¿Recordarme?";
  static const forgotPassword1 = "¿Olvidaste la contraseña?";
  static const dontHaveAccount = "¿No tienes una cuenta? ";
  static const signUp = "Regístrate";
  static const phone = "Teléfono";
  static const phoneHint = "+44 258 6649 565";
  static const passwordHint = "*** *** ***";
  static const start = "Iniciar";
  static const Continue = "Continuar";
  static const type = "Escribe";
  static const speak = "Habla";
  static const submitYourAnswer = "Envía tu respuesta";
  static const typeYourAnswer = "Escribe tu respuesta";
  static const congratulations = "¡Felicidades!";
  static const totalXP = "XP total";
  static const amazing = "Increíble";
  static const earnedGems = "Gemas obtenidas";
  static const shareResults = "Compartir resultados";
  static const takeNewQuiz = "Tomar nuevo cuestionario";
  static const gotIt = "Entendido";
  static const holdToSpeak = "Mantén para hablar";
  static const leaderboard = "Clasificación";
  static const lessonQuests = "Misiones de lecciones";
  static const autoTrackedQuests = "Misiones auto-seguidas";
  static const gemsAvailable = "Gemas disponibles";
  static const exchange = "Intercambiar";
  static const heartRecharge = "Recargar corazones";
  static const restoreAllHeart =
      "Restaura todos los corazones para continuar aprendiendo";
  static const heartsFull = "Corazones llenos";
  static const alreadyMaxHeart = "Tus corazones ya están al máximo";
  static const premiumSubscription = "Suscripción premium";
  static const popular = "Popular";
  static const removeAdsUnlockPremium =
      "Elimina anuncios y desbloquea funciones premium";
  static const perMonth = "Por mes";
  static const subscribe = "Suscribirse";
  static const gemToUSD = "Gema a USD";
  static const youCanWithDraw = "Puedes retirar: ";
  static const paypalEmail = "Tu correo de PayPal";
  static const withdrawToPayPal = "Retirar a PayPal";
  static const selectPaymentGateway = "Seleccionar método de pago";
  static const addNew = "Agregar nuevo";
  static const paymentMethod = "Nuevo método de pago";
  static const aiPersonalityAnalysis = "Análisis de personalidad por IA";

  static const getPersonalizedInsights =
      "¡Obtén información personalizada basada en tus respuestas introductorias y chats!";
  static const friends = "Amigos";
  static const squadTogether = "¡Reúne a tu equipo!";
  static const inviteFriends = "Invitar amigos";
  static const YourStats = "Tus estadísticas";
  static const Hearts = "Corazones";
  static const Level = "Nivel";
  static const DaySteark = "Racha diaria";
  static const XP = "XP";
  static const AccountDetails = "Detalles de la cuenta";
  static const PersonalInfo = "Información personal";
  static const Notification = "Notificación";
  static const referAFriend = "Recomendar a un amigo";
  static const SettingsAccessibility = "Ajustes y accesibilidad";
  static const DarkMode = "Modo oscuro";
  static const Voiceover = "Narración";
  static const Earn = "Ganar";
  static const MyBalance = "Mi saldo";
  static const Support = "Soporte";
  static const ContactUS = "Contáctanos";
  static const LogOut = "Cerrar sesión";
  static const RefreshAnalysis = "Actualizar análisis";
  static const Phone = "Teléfono : +44 234 563 45";
  static const Birthday = "Fecha de nacimiento : 12/05/1996";
  static const country = "País : Reino Unido";
  static const Save = "Guardar";
  static const AvailableBalance = "Saldo disponible";
  static const Withdarw = "Retirar";
  static const Activity = "Actividad";
  static const Received = "Recibido";
  static const Requested = "Solicitado";
  static const Rejected = "Rechazado";
  static const Pending = "Pendiente";
  static const SubmitRequest = "Enviar solicitud";
  static const Amount = "Monto";
  static const PaymentMethod = "Método de pago";
  static const Notifications = "Notificaciones";
  static const Today = "Hoy";
  static const Yesterday = "Ayer";
  static const ContactUs = "Contáctanos";
  static const writeInCommentBox = "Escribe en el cuadro de abajo";
  static const enterIssueTitle = "Introduce el título de tu problema";
  static const Title = "Título";
  static const Writehere = "Escribe aquí...";
  static const Send = "Enviar";
  static const ReferFriend = "Recomienda a un amigo";
  static const ReferFriendAndGetOff =
      "Recomienda a un amigo y obtén 50% de descuento";
  static const Refer = "Recomendar";
}